name: Fixed CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        id: build-image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t cicd-test:latest .
          IMAGE_ID=$(docker images -q cicd-test:latest)
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Test Docker Image
        run: |
          docker run --rm cicd-test:latest python test_main.py

      - name: Push Docker Image
        run: |
          docker tag cicd-test:latest ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
