name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  login: #1
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build: #3
    runs-on: ubuntu-latest
    needs: login
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest .

      - name: Subir la imagen a Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest

  test: #4
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Ejecutar pruebas unitarias
        run: python -m unittest discover -s . -p "test_*.py"

  test-docker: #4
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Probar el contenedor Docker (Ejecutar pruebas dentro del contenedor)
        run: docker run --rm ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest python -m unittest discover -s . -p "test_*.py"
#  push: #5
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Subir la imagen a Docker Hub
#        run: |
#          docker tag cicd-test docker.io/<tu-usuario>/cicd-test:latest
#          docker push docker.io/<tu-usuario>/cicd-test:latest

