name: Docker CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Construir la imagen Docker
        run: docker build -t cicd-test .

      - name: Probar el contenedor Docker
        run: docker run --rm cicd-test

      - name: Ejecutar Pruebas
        run: python -m unittest discover -s . -p "test_*.py"
