name: CI/CD Pipeline with Metadata Analysis

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5. Check if base image exists
      - name: Check if base image exists
        id: check-image
        run: |
          if docker manifest inspect ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest > /dev/null 2>&1; then
            echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
          fi

      # 6. Analyze base image metadata
      - name: Analyze base image metadata
        if: env.IMAGE_EXISTS == 'true'
        run: |
          python analyze_image.py ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest

      # 7. Import base image
      - name: Import base image
        if: env.IMAGE_EXISTS == 'true'
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
          echo "Base image imported successfully."

      # 8. Build Docker Image
      - name: Build Docker Image
        id: build-image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t cicd-test:latest .
          IMAGE_ID=$(docker images -q cicd-test:latest)
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      # 9. Test Docker Image
      - name: Test Docker Image
        run: |
          docker run --rm cicd-test:latest python test_main.py

      # 10. Push Docker Image
      - name: Push Docker Image
        run: |
          docker tag cicd-test:latest ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest

      # 11. Analyze pushed image metadata
      - name: Analyze pushed image metadata
        run: |
          python analyze_image.py ${{ secrets.DOCKER_USERNAME }}/cicd-test:latest

      # 12. Cleanup
      - name: Cleanup Docker
        run: |
          docker rmi cicd-test:latest || true
